export const simpleDoctorsData = [
  {
    id: '1',
    name: 'Иванов Алексей Петрович',
    specialty: 'Кардиолог',
    experience: 15,
    rating: 4.8,
    reviewsCount: 24,
    price: 2500,
    nextAvailable: 'Сегодня, 15:00',
    description: 'Специалист по заболеваниям сердечно-сосудистой системы. Проводит диагностику и лечение артериальной гипертензии, ишемической болезни сердца.',
    photoUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: '2',
    name: 'Петрова Мария Владимировна',
    specialty: 'Невролог',
    experience: 8,
    rating: 4.9,
    reviewsCount: 18,
    price: 2200,
    nextAvailable: 'Завтра, 10:30',
    description: 'Диагностика и лечение заболеваний нервной системы. Специализируется на головных болях, нарушениях сна, вегетососудистой дистонии.',
    photoUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: '3',
    name: 'Сидоров Дмитрий Николаевич',
    specialty: 'Терапевт',
    experience: 12,
    rating: 4.7,
    reviewsCount: 32,
    price: 1800,
    nextAvailable: 'Сегодня, 17:00',
    description: 'Врач общей практики. Проводит первичный осмотр, диагностику и лечение широкого спектра заболеваний внутренних органов.',
    photoUrl: null,
  },
  {
    id: '4',
    name: 'Козлова Анна Сергеевна',
    specialty: 'Офтальмолог',
    experience: 6,
    rating: 4.6,
    reviewsCount: 15,
    price: 2000,
    nextAvailable: 'Завтра, 14:15',
    description: 'Специалист по диагностике и лечению заболеваний глаз. Проводит подбор очков и контактных линз.',
    photoUrl: 'https://images.unsplash.com/photo-1594824947933-d0501ba2fe65?w=150&h=150&fit=crop&crop=face',
  },
];

export const simpleSpecialties = [
  'Все',
  'Кардиолог',
  'Невролог',
  'Терапевт',
  'Офтальмолог',
  'Хирург',
  'Педиатр',
  'Гастроэнтеролог',
];